### ISSUE TITLE
Kernel is vulnerable to starvation in some cases

### ISSUE THREAD

**Issue by ZhukovAlexander** [dabeaz/curio#112]
While working on [this PR](https://github.com/dabeaz/curio/pull/110) I was able to forge some code that made the event loop to completely skip the IO step. Here is the code that was used:

```python
import curio


lck = curio.Lock()

async def do_nothing():
    await curio.sleep(0)

async def worker(name):
    while True:
        async with lck:
            await curio.spawn(do_nothing())

async def main():
    await curio.spawn(worker('foo'))
    await curio.spawn(worker('bar'))


if __name__ == '__main__':
    curio.run(main())

```
The above program just runs forever without ever entering the IO polling phase. The root cause of it is that kernel uses greedy approach when running ready task, meaning, it will skip the IO completely, if there is at least one task ready to run ([relevant lines](https://github.com/dabeaz/curio/blob/master/curio/kernel.py#L623)). For reference, some libraries make sure to poll for IO for at least some minimal amount of time to give IO coroutines a chance to run.

**Comment by dabeaz** [comment]
I'm somewhat less concerned with scheduling of locks/queues like this because I can't really envision a real-world situation where a program would just be spinning forever on a lock and never performing any I/O (a program like that would end up be 100% cpu-bound which is definitely not the kind of thing you'd want to run on Curio).     That said, I suppose the code could poll for I/O on rescheduling.   I don't know.  Open to thoughts.

**Comment by njsmith** [comment]
I guess it might make sense to make lock acquisition a guaranteed schedule point, if we make a blanket rule that all potentially blocking operations are schedule points. But yeah, it's always going to be possible to write weird code that blocks the kernel -- the obvious example is just
```python
async def worker():
    while True:
         pass
```
:-)

So the question is more about coming up with more-nuanced guidance to users, so that they can look at a piece of code and make a clear prediction about whether it will be a problem or not, and where usually the answer is "not a problem".

**Comment by njsmith** [comment]
Here's another starvation case. It's not realistic, but the effect is still a bit surprising. We have two tasks that talk to each other (here they happen to be identical, but you can imagine them implementing some sort of RPC pattern or something), and they actually *block* on each iteration -- i.e., are removed entirely from the ready queue. So you'd think they couldn't starve the kernel! Yet together they do, because they take turns putting each other back onto the ready queue, so that it never empties out:

```python
import curio

async def watchdog():
    i = 0
    while True:
        print("Event loop is live after {} seconds".format(i))
        i += 1
        await curio.sleep(1)

async def ping(inq, outq):
    while True:
        obj = await inq.get()
        # ... do some processing ...
        await outq.put(obj)

async def pong(inq, outq):
    while True:
        obj = await inq.get()
        # ... do some processing ...
        await outq.put(obj)

async def main():
    q1 = curio.Queue()
    q2 = curio.Queue()
    await q1.put("something")
    await curio.spawn(watchdog())
    await curio.spawn(ping(q1, q2))
    await curio.spawn(pong(q2, q1))

curio.run(main())
```

It prints "Event loop is live" once, and then goes silent. If we add a call to `curio.sleep(0)` inside of either of the `ping` / `pong` tasks (doesn't matter which one) then it starts printing the message once a second, as intended.

I guess this could be an argument for splitting the ready queue into two pieces: a "current" queue and a "pending" queue. The idea would be that when a task becomes runnable it goes onto the pending queue, never the current queue. The current queue gets processed until its empty, and then gets refilled by checking for I/O + timeouts + the pending queue. So that would enforce the invariant that any single task can't get scheduled twice without an I/O check in between. I don't know if it would affect any realistic cases, but it would certainly make it easier to prove that these kinds of weird cases aren't lurking :-)

(I discovered this while I was trying to figure out how to reliably print a diagnostic if some task blocks the event loop for too long. Specifically I was trying to figure out whether I should measure the time taken in an individual task execution (advantage: if a task does starve the kernel, we know who to blame), or the time between I/O checks (advantage: can catch multi-task pathologies like this).)

**Comment by imrn** [comment]
On 11/16/16, Nathaniel J. Smith <notifications@github.com> wrote:
> Here's another starvation case. It's not realistic, but the effect is still
> a bit surprising.

Realistic or not "Torture testing" surely improves predictability.

**Comment by ZhukovAlexander** [comment]
Closing this as it needs some realworld evidence.
