### ISSUE TITLE
clean way to access results from curio.gather()

### ISSUE THREAD

**Issue by goldcode** [dabeaz/curio#125]
I have x tasks and im only interested in task2
```
async def fn():
    task1 = await curio.spawn(coro1())
    task2 = await curio.spawn(coro2())
    taskx = await curio.spawn(corox())        
    await curio.gather([task1, task2, taskx])
```
what would be the best way to access the results of only task2? I would use task2.next_value but it doesnt sound like a variable which contain results. so i'm guessing it shouldn't be used?

P.S. I'm using the library in a device software prototype project controlling cameras, lasers and stepper motors. I appreciate your good work.

**Comment by ZhukovAlexander** [comment]
`gather` will return a list of results. You just have to pick the one you're interested in. Here is what you need:

```python
async def fn():
    task1 = await curio.spawn(coro1())
    task2 = await curio.spawn(coro2())
    taskx = await curio.spawn(corox())

    # this will return a list of results for each task
    return await curio.gather([task1, task2, taskx])

# this will print a result of the second task
print(curio.run(fn())[1])
```

**Comment by goldcode** [comment]
`print(curio.run(fn())[1])`
ok. i hoped there would be another way. When i made my own homemade 'coroutine driver', the gather functionality returned a dictionary of {task:result}. this way i could access the results without bothering about keeping track of indices which in my usage is more an obstacle.
e.g. 
```
camera_task = await curio.spawn(coro_camera())
image = (await curio.gather([task1, camera_task, taskx]))[camera_task]
```


concretely hear i expect an image.

**Comment by dabeaz** [comment]
You could always do this:

    async def gatherd(tasks):
         results = await gather(tasks)
         return { task: result for task, result in zip(tasks, results) }

    image = (await gatherd([task1, camera_task, taskx]))[camera_task]

The `gather()` function is fairly new in curio.   Not opposed to making a dictionary version of it (although would need to think of a sensible name--not sure about `gatherd`).

**Comment by njsmith** [comment]
If you have access to the task object you're interested in then you don't
need to do the lookup at all: just call task2.join(). OTOH if you don't
have the task object then I guess a dictionary indexed by task objects
isn't very useful. So I'm not really seeing a use case for 'gatherd'.

**Comment by goldcode** [comment]
_just call task2.join()._ 
you  mean don't use gather at all? i prefer using gather because for me it better conveys that all tasks are running freely as opposed to dabeaz's code in https://github.com/dabeaz/curio/issues/36 where result = await task.join() gives the 'impression' that the tasks are getting serialized. 

i guess the 'join' hard wires my brain into thinking blocking without recognizing the await next to it. maybe i should just get used to it. but then again the next colleague will stumble on it again... ;)

@dabeaz 
thanks, i could use a wrapper like gatherd.

**Comment by njsmith** [comment]
You can use gather or not as you prefer. After a task has finished you can
still call .join() whenever you want, as many times as you want.

**Comment by goldcode** [comment]
_call .join() whenever you want_
thanks. i didn't realize this. is the turnaround time for this call dependent on the number of other tasks running? would it be as fast as a key lookup via gatherd?

**Comment by njsmith** [comment]
You can see for yourself :-): https://github.com/dabeaz/curio/blob/3cc8acbc40fc07404459e87177774de6549aa5ba/curio/task.py#L65-L74

I guess you also need to know that `_join_task` is a kernel trap that blocks until the given task has exited; you can see [its implementation here](https://github.com/dabeaz/curio/blob/3cc8acbc40fc07404459e87177774de6549aa5ba/curio/kernel.py#L485-L491).

In this case, `_join_task` will exit immediately because `task.terminated` is true, and then `join` will just return `task2.next_value`. All of these operations are O(1) -- they don't depend on the number of tasks running. It'll be slower than a key lookup via gatherd because `join` is a blocking trap that triggers rescheduling etc., but this is unlikely to matter in practice. (In fact, if the speed of `join` *does* matter, and you really only care about the one task, then you shouldn't be calling `gather`, because if you look at the source for `gather` you'll see that it calls `join` on all of those other tasks that you don't care about.)
