### ISSUE TITLE
[DISCUSSION] Should we make a Kernel thread-safe?

### ISSUE THREAD

**Issue by ZhukovAlexander** [dabeaz/curio#131]
While `curio.run` is definitely thread-safe by definition, using manually created `Kernel` instance is not thread safe. User can create an instance of a `Kernel` and call `Kernel.run()` is multiple different threads. Should curio restrict this? Or this is another evil and only hypothetically-possible corner case?

**Comment by dabeaz** [comment]
I suppose the `run()` method could be restricted by a threading RLock or something.   To be honest, I haven't given it much thought---although part of the reason for the insular nature of the current `run()` method was to make it practically impossible for anything (especially threads) to externally interact with the kernel except via async/await.

**Comment by njsmith** [comment]
I don't think it's worth the effort to add a lock inside Kernel.run, or
that it would be very helpful to users. Most objects in Python are unsafe
to simultaneously call methods on from different threads, unless they
explicitly say otherwise. The convention is that if you want to start
messing about with an object from multiple threads, then it's your
responsibility to come up with some locking strategy.

**Comment by imrn** [comment]
Concurrent programming invented by the guys who say:
"Hey look: We are so clever that we can partition our code in
a way none of the parts step on others feet (that's threading).
And even we reached the nirvana where we can cram them all into
a single thread and keep all going. (that's async prog.)"

So by definition the kernel should stay way dealing anything
outside its scope. Its programmers responsibility to
protect it from nonsense.

**Comment by dabeaz** [comment]
Closing for now.  If needed the `run()` method can be protected by a lock from the outside.
