### ISSUE TITLE
Return (Val, Err) on all awaits. Eliminate exceptions.

### ISSUE THREAD

**Issue by imrn** [dabeaz/curio#140]
This means changing many things. Yes, I can use
such a pattern in my own application without
any support in Curio. But Curio may also
consider using such a convention. Why? Does it
worth it? Let's talk:

- Because exceptions are ugly.

- This is how rust handles errors. (sort of)
https://doc.rust-lang.org/book/error-handling.html

- Infact, I dont like the name "Err". Because as I'm
writing this, I'm also planning to use it as a means of
communicating with the task. The structure
of the Message object, as well as the api for
sending it, is wide open for suggestions.

- Of course Curio can send its own error messages in a
similar way.

```python
async def someasyncfunc():
    while True:
        ret, msg = await forsomething()
        if msg.content == 'cancel':
            await msg.sendingtask.respond('ok_sir')
            return
        else:
            await msg.sendingtask.respond('cant_hear_you')
            continue

task = await spawn(someasyncfunc())
result = await task.sendmessage('cancel')
```

**Comment by dabeaz** [comment]
Although I can appreciate the reasons why other languages might choose to use return codes, I don't see this as a change that I would ever make in Curio.

The main issue is that return codes are not the standard "pythonic" way of handling errors.  If something other than exceptions are used, I fear that it's going to cause no end of weird usability problems later simply because it's not the standard way of doing things.   Also, many parts of curio aim to emulate functionality from other parts of the standard library (i.e., sockets, subprocesses, etc.).   Exceptions are used there and curio aims to copy that.  

On a personal note as a former C programmer, I really don't want to go back to the world of return codes.  So, that's also a consideration ;-).

**Comment by imrn** [comment]
Of course it's absolutely not pythonic. Infact I've been waiting for 
this response.. ;) I proposed it as general solution for the other
issues related with task/exception management, queues, links,
mailboxes and so forth.
Anyway, it is not a big deal for me to use it where it makes really
good sense. This issue serves as for historic record.. Thanks.
