### ISSUE TITLE
`kernel.run(shutdown=True)` raises AssertionError if daemon thread tasks are still left

### ISSUE THREAD

**Issue by SunDwarf** [dabeaz/curio#151]
Whilst trying to reliably reproduce #150, I found a different bug:

```
import queue
import curio
q = queue.Queue()
async def _worker():
    await curio.abide(q.get)
async def _main():
    await curio.spawn(_worker(), daemon=True)
kernel = curio.Kernel()
kernel.run(_main(), shutdown=True)
```

```
Traceback (most recent call last):
  File "/tmp/aa.py", line 14, in <module>
    kernel.run(_main(), shutdown=True)
  File "/media/storage/eyes/virtualenv/curio_dev/lib/python3.5/site-packages/curio/kernel.py", line 940, in run
    _shutdown()
  File "/media/storage/eyes/virtualenv/curio_dev/lib/python3.5/site-packages/curio/kernel.py", line 456, in _shutdown
    assert not tasks
AssertionError
```

**Comment by dabeaz** [comment]
Curious.  This is being caused by a number of factors, but part of it is the fact that the `_worker()` doesn't start running until after the `_main()` coroutine has already terminated (and it initiates the launch of the in-kernel loopback task).

This could be fixed if `spawn()` reverts to behavior of always guaranteeing that the spawned task is running before returning. 

Let me think about it.

**Comment by dabeaz** [comment]
Fixed.
