### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by TiberiumPY** [dabeaz/curio#166]
Hi, is there any curio benchmarks?
I'm curious how they will perform under PyPy3.5 pre-alpha (has almost all 3.5 features + f-strings from 3.6 already)

**Comment by dabeaz** [comment]
There are some benchmarks in the curio/examples/bench directory.   These are  mostly the same benchmarks that were posted for some testing with uvloop and asyncio.  Run a program such as `curioecho.py` and then run the program `uvclient.py`.   Would be interested to see what happens under PyPy.

**Comment by TiberiumPY** [comment]
@dabeaz right now PyPy3.5 is ~4 times slower.
I expected results like this, because PyPy team hasn't started optimizing PyPy3.5 yet.
I think they can implement selectors in RPython instead of using Python version

**Comment by dabeaz** [comment]
Closing just to clear out issues.  Benchmarks with PyPy will be interesting as that project catches up with Python3.5 though

**Comment by TiberiumPY** [comment]
@dabeaz (there's already a nightly PyPy3 with Python 3.5 support)
So I tried curioecho.py and asyncecho.py on PyPy3, and it seems that asyncecho is faster 6 times than curioecho (don't know the reason though)
So there are the results:
curioecho.py -> PyPy3: 11081 RPS, Python 3.6 (not tested, because it fails to run curioecho on my PC)
asyncecho.py -> PyPy3: 60786 RPS, Python 3.6: 23535 RPS

**Comment by dabeaz** [comment]
Really hard to say without knowing more information about the runtime environment and other settings (what OS, what run parameters, etc.).   Also, it's a trivial benchmark.   One might look at the benchmarks published on the PyPy blog for more substantial work.  https://morepypy.blogspot.com.br/2017/03/async-http-benchmarks-on-pypy3.html

**Comment by njsmith** [comment]
It's unfortunate that you couldn't get CPython numbers for curio, but we
know that on CPython curio generally beats asyncio for this benchmark.
Given that, it's really weird that your curio pypy numbers are slower than
your asyncio *CPython* numbers -- it suggests that in the curio version of
this benchmark, pypy is slower than CPython, which is really unusual, and
suggests some bug in pypy that they'll probably want to know about.

Actually now that I think about it, I think @squeaky_pl mentioned seeing
something similar for his curio http server benchmark? Like it worked great
under pypy in his original benchmark, but in a simplified benchmark that
just hit one page over and over, curio+pypy performance fell off a cliff?
There probably is something to track down here (though I suspect it's a
pypy bug rather than a curio bug).
