### ISSUE TITLE
New Release. Also, thinking about project scope

### ISSUE THREAD

**Issue by dabeaz** [dabeaz/curio#249]
Just a heads up that I will be making a new Curio release fairly soon.  With that in mind, I've also been doing a bit of thinking about the overall scope of the project and the whole library vs. framework issue.  It has always been my view that Curio should be more of a low-level library that provides a basic set of functionality related to concurrency and I/O from which one could build more interesting things (as opposed to being a budding framework that trying to do everything).  Thus, I've been doing some project cleanup that involves removing some of the current functionality, moving some other things over to the examples directory and generally trying to make Curio leaner.

I don't have an exact ETA for the new release, but it will happen sometime in February.

**Comment by SunDwarf** [comment]
What (if) anything else is going to be removed in cleanup pre-next release?

**Comment by ProtonScott** [comment]
I’d be interested if it’s possibke to get a heads up in that.

I what I can tell you specifically in regards to the question of the future is this:

I use the subprocess, ssl, the aopen function and socket module a lot. 

I like the idea behind Kernel as the more powerful way of controlling events/loops. Is this intended to be subclassible?

I’d love if there was a way to subclass a TCP server tho I suspect limitations around the std libs docket module might be more to blame here.

I am always game for more transparent ways to handle sockets. 

I use zeromq extensively professionally and their official library runs with curio fine. I dunno if you need to maintain yours? I just mention that only because I love what you have done with Channel and I think it’s far more interesting.

For the moment that’s what i got I may come back and respond with more as I think about this

**Comment by dabeaz** [comment]
Probably the big, and maybe controversial, removal is that I'm going to nix Locals.   The implementation is already problematic in light of curio's mix of async, threads, and processes.  There is also a PEP and the addition of contextvars in Python 3.7.  So, all things equal, I'd prefer to push people towards that as opposed to maintaining a curio-specific version of it.

Basic sockets and I/O will stay, but anything that resembles an "application level" protocol (i.e., HTTP, ZeroMQ, Redis, etc.) would be moved to separate projects.  At the moment, that only applies to the ZeroMQ submodule I cooked up.   I'm more interested in trying to keep a "stable" core of basic functionality as opposed to "Curio" being an umbrella project for every possible protocol or application.

On subclassing TCP servers, I'm game for thinking about ways to customize that further. Same goes for Channel objects.

On the Kernel, one of the initial goals of the project was to make the Kernel as invisible as possible--partly in reaction to the complexity and oversized role of the event loop instance in asyncio.  But also viewing it more like an opaque environment much like the kernel in an operating system (it's in charge, but async tasks don't really get a hook to look inside or interact with it directly).   I'm also trying to do as little as possible in "kernel space" as possible. Aside from basic task switching and scheduling, there's not much going on there.

I'm a bit curious to know what you might be thinking on subclassing the kernel.  There are certain hooks by which one can do custom things with the kernel.  I have also implemented different kernels as experiments.  For example, I've written a version of the Curio kernel entirely as a C extension (which was interesting, but not interesting enough for me to actively pursue it further at this time).

**Comment by ProtonScott** [comment]
I’ll try and answer quickly as I’m gonna be out of touch for a good week until Friday so I don’t want to leave this unanswered but I may come back and add to this discussion if possible.

As far as TVP goes I think I stress of a function that generates the Socket object having even a thinnish wrapper around this for TCP/UDP/Unix sockets as like a malleable class would make working with sockets just less clunky. Right now I have an async function that generates a socket then hands it to like a “server” class if you will or an “io” class or what have you. As I see this and I think from your statements you do too in some ways but please correct me if I’m wrong - this is a library for people to build upon something that they then may share with others, it makes the downstream efforts much more easier and transparent to work with because ultimately if I produce work win this let’s say and it’s going to be used by my colleagues the less they need to stare at internals the better. That’s how I think of this anyway. Even if a TCP/UDP/Socket class just basically proxies the socket.socket() return object and matched its methods (eg sendfile for instance) they would be good enough to build on structurally speaking. I can hen further abstract that as a framework/module/library Dev.

With channels maybe think of it as a pub/sub thing kind of like zeromq. In practice it feels similar and right now I feel like it does well there but I’m looking at just cleaning that up for modularities sake perhaps?

As for the kernel: it’s kodtly related to the run method. In the docs you describe that one should use Kernel.run() in scenarios of having heavy computation or lots of different connection points (that’s how I read it anyway). If I want to customize that at all it doesn’t feel transparent to me how I should do that. Maybe decouple that to a Run class instead? Even if it just proxies Kernel.

And as a gentle aside, I usually can tell the difference if I’m suppose to touch something or not if it’s named with an underscore or two underscores. Perhaps objects we aren’t supposed to really use might be renamed to say `_Kernel` Of similar? That’s not critical obviously

**Comment by ProtonScott** [comment]
@dabeaz  should I pull request a Run class or is this something we still want to discuss?

**Comment by dabeaz** [comment]
Need more time to review and discuss.

**Comment by dabeaz** [comment]
Can you show me some usage examples of what this would look like?   At a high level, I don't want curio to have a lot of extra plumbing involving objects just to get things running.  Right now, there are two basic modes of operation.  One option is to run a single coroutine.  This creates the kernel, runs the coroutine, shuts down the kernel.

     run(coro)

Or you can submit multiple coroutines to a single kernel:

    with Kernel() as kern:
            kern.run(coro1)
            kern.run(coro2)
            ...

Both are pretty simple in my opinion. What extra thing is the Run class giving me?

**Comment by ProtonScott** [comment]
I'm planning on mocking up a more complete version of this later. In essence it boils down to having 1 entry point to the Kernel without having to think about whether I should use a context manager or not. A run class would allow you to do like `Run(func, *args)` or `Run((func1, func1, func3...),*args)`

Just less for the end user to have to keep track of. I'm still working out the argument kinks but thats what it boils down to. If you feel like its not worth pursuing though I understand.

**Comment by Fuyukai** [comment]
Has this been pushed back to this month? The task group changes are blocking a new ver of one of my projects currently.

**Comment by dabeaz** [comment]
I'd like to make a new release before next week because I'm going back into more of a teaching schedule.    However, tell me more about this "task group change" issue.  Is something in the current Github curio broken?

**Comment by Fuyukai** [comment]
The opposite; I need #239's fix but it's only available on the current git release, and not the stable release.

**Comment by dabeaz** [comment]
I just pushed a new release.    There are a variety of things I still want to do, but I'm going into a period of teaching and won't much time to work in the short-term.   Curio currently passes all tests on Python-3.5, 3.6, and 3.7b2 so now seems as good a time as any to push something.
