### ISSUE TITLE
io.Stream fails on Windows

### ISSUE THREAD

**Issue by roger-** [dabeaz/curio#32]
`os.set_blocking` is missing on Windows, which causes [this call](https://github.com/dabeaz/curio/blob/master/curio/io.py#L276) in io.py to fail:

``` python
    os.set_blocking(self._fileno, False)
```

**Comment by dabeaz** [comment]
Curio has never been tested on Windows and is likely to experience a lot of problems with files, signal handling, the loopback socket, and other internal features.   The documentation is pretty clear about Unix being required at this point.

**Comment by roger-** [comment]
Ah, I must have missed that. 

For what it's worth this is the first issue thats come up for me; otherwise it works quite well in Windows.

**Comment by dabeaz** [comment]
It's interesting that it works.   On the whole, it will probably work okay for purely socket-based code.  The portability issues that I know about with Windows are this:

-  I/O polling probably doesn't work with non-socket objects like files, streams, etc.
-  The socketpair() function traditionally hasn't been portable and needs to be changed to make it possible to wait for Futures associated with threads and subprocesses.
- Anything related to signal handling probably won't work at all.

It might be possible to have some file I/O polling if curio borrowed some techniques from other libraries such as Twisted or Tornado (would need to investigate further).    The socketpair() portability issue can be fixed in a pretty straightforward way.
