### ISSUE TITLE
Curio monitor does not work in windows.

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [dabeaz/curio#40]
```
Curio: Task Crash: monitor
Traceback (most recent call last):
    File "c:\Miniconda3\lib\site-packages\curio\kernel.py", line 365, in run
      op, *args = current.coro.send(current.next_value)
    File "c:\Miniconda3\lib\site-packages\curio\monitor.py", line 143, in monitor
      await monrun(kernel)
    File "c:\Miniconda3\lib\site-packages\curio\monitor.py", line 70, in monrun
      stdin = Stream(sys.stdin.buffer.raw)
    File "c:\Miniconda3\lib\site-packages\curio\io.py", line 276, in __init__
      os.set_blocking(self._fileno, False)
AttributeError: module 'os' has no attribute 'set_blocking'
```

**Comment by dabeaz** [comment]
As currently written, the curio monitor will not work on Windows because there is no support for non-blocking I/O or polling on anything but sockets.   It might be possible to hack a different kind of event loop.  Another option might be to modify the monitor so that it is accessible via a socket using telnet or some equivalent.   

Just as a note: curio has not been tested or developed on Windows.  This is not the only thing that would likely be broken.

**Comment by UNDEFINED-BEHAVIOR** [comment]
Thank you for the clarification.

There are literally just a single sentence hinting that the framework is not cross-platform and only 
intended to be used on Unix environment. I think there should be a more explicit warning statement in the documentation so that people won't mistaken it for bugs.
