### ISSUE TITLE
example on files?

### ISSUE THREAD

**Issue by fwang2** [dabeaz/curio#43]
The README page suggests that the curio can work with files, is it possible to add an example for what kind of cooperative I/O can be accomplished?

**Comment by dabeaz** [comment]
This is referring to any Unix file descriptor which could mean many different things including files, pipes, TTYs, sockets, etc.   That said, it's not likely that curio could be usefully applied to reading an actual file (as in file on the filesystem) since asynchronous file I/O is either unimplemented or implemented using a different API than the one curio uses.
