### ISSUE TITLE
Using py.test for Unit Tests

### ISSUE THREAD

**Issue by dabeaz** [dabeaz/curio#45]
Thinking about switching to py.test for the tests.  No particular reason other than having a more concrete excuse to use and learn more about py.test.   Thoughts?

**Comment by kdart** [comment]
I recently started using it. I like it. I think that would be a good idea.

**Comment by johnnoone** [comment]
pytest is the way to go, it is pythonic, easy to write, easy to read.

You may be interested in a plugin I wrote for testing curio based coroutine.
It is called [pytest-curio](https://pypi.python.org/pypi/pytest-curio), it's inspired by [pytest-asyncio](https://pypi.python.org/pypi/pytest-asyncio). The code source is published here https://lab.errorist.xyz/pytest/pytest-curio and there https://github.com/johnnoone/pytest-curio.

**Comment by tds333** [comment]
py.test is one of the best test libraries for Python. I use it since years and also for a large test suite. It scales very well and has superior features. Also the support if there is a bug is superior. In most cases it was fixed in one day and a new release with the fixes some days later. Normal Python unittests are also supported so a switch can be done step by step.

**Comment by dabeaz** [comment]
I'm going to do it.  Because, why not?  And it seems easy enough.

**Comment by brettcannon** [comment]
Is there any work left to be done for this, @dabeaz ?

**Comment by dabeaz** [comment]
I've been using pytest for the last couple of months with Curio.  It seems to work fine.   There is probably some room to explore better ways of writing test-fixtures for Curio.  Although there are tests, they feel a bit hacky to me.   It's definitely something that could be looked at further.
